name: Patch_Kernel_KPM

on:
  workflow_run:
    workflows:
      - "Build OnePlus Nord 3 Stock"
      - "Build OnePlus Nord 3 Crom"
    types:
      - completed

jobs:
  # This new job checks the result of the triggering workflow first
  check_trigger:
    name: Verify Build Result
    runs-on: ubuntu-latest
    steps:
      - name: Check if build was successful
        if: github.event.workflow_run.conclusion != 'success'
        run: |
          echo "Triggering workflow was not successful (conclusion: ${{ github.event.workflow_run.conclusion }}). Stopping."
          exit 1
  release:
    name: Create Release
    needs: check_trigger
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Get current time
        id: get_time
        run: echo "timestamp=$(TZ='Asia/Kolkata' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

     


      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts from Completed Build
        run: |
          gh run download ${{ github.event.workflow_run.id }} --dir ./downloaded-artifacts --repo ${{ github.repository }}
      
      - name: Find Artifact Name
        id: find_artifact
        run: |
          ARTIFACT_DIR=$(ls -d ./downloaded-artifacts/*/)
          ARTIFACT_NAME=$(basename "$ARTIFACT_DIR")
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

      - name: Apply patch_linux and replace Image
        run: |
          cd downloaded-artifacts/${{ steps.find_artifact.outputs.artifact_name }}
          curl -LO --retry 5 https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/main/kpm/patch_linux
          chmod +x patch_linux
          gzip -d Image.gz
          ./patch_linux
          rm -f Image.gz
          mv oImage Image
          gzip -f -9 Image

      - name: Make AnyKernel3 ZIP
        run: |
          git clone https://github.com/darklord4567/Anykernel3_STOCK_NORD3 --depth=1
          cp downloaded-artifacts/${{ steps.find_artifact.outputs.artifact_name }}/Image.gz Anykernel3_STOCK_NORD3/Image.gz

      - name: Upload Patched Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find_artifact.outputs.artifact_name }}
          path: ./Anykernel3_STOCK_NORD3/*

  notify_result:
    name: Notify Patch Status
    needs: release
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Success
        if: ${{ needs.release.result == 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID_PERSONAL }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            *✅ Patching Successful*
            ------------------------------------
            The patched kernel artifact is ready. Starting the final `Create Kernel Release` workflow.

      - name: Notify on Failure, Cancellation, or Skip
        # This condition now checks for all non-success outcomes
        if: ${{ needs.release.result == 'failure' || needs.release.result == 'cancelled' || needs.release.result == 'skipped' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID_PERSONAL }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            *❌ Patching Workflow Did Not Complete*
            ------------------------------------
            The patching process was not successful (Status: ${{ needs.release.result }}).
            The release process will not start.
            [View Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
